cd /mnt/fsx/youtu-agent/jiaxicao/SDPO
export TENSORBOARD_DIR=/mnt/fsx/youtu-agent/jiaxicao/tensorboard/grpo-ucsdpoaux-taco-qwen3-8b-emajf-vllm-h200-6400-260603
export ROLLOUT_DIR=/mnt/fsx/youtu-agent/jiaxicao/rollouts/grpo-ucsdpoaux-taco-qwen3-8b-emajf-vllm-h200-6400-260603
export TOKENIZERS_PARALLELISM=false
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export NCCL_SOCKET_IFNAME=eth0
export GLOO_SOCKET_IFNAME=eth0
bash training/verl_training.sh \
  grpo-ucsdpoaux-taco-qwen3-8b-emajf-vllm-h200-6400-260603 \
  sdpo \
  datasets/taco \
  vars.dir=/mnt/fsx/youtu-agent/jiaxicao/SDPO \
  trainer.n_gpus_per_node=8 \
  actor_rollout_ref.model.path=/mnt/fsx/youtu-agent/public-model/Qwen/Qwen3-8B \
  critic.model.path=/mnt/fsx/youtu-agent/public-model/Qwen/Qwen3-8B \
  data.train_batch_size=64 \
  data.train_max_samples=6400 \
  data.seed=42 \
  actor_rollout_ref.rollout.n=8 \
  actor_rollout_ref.actor.ppo_mini_batch_size=64 \
  actor_rollout_ref.actor.optim.lr=2e-6 \
  actor_rollout_ref.actor.optim.lr_warmup_steps=10 \
  data.max_response_length=8192 \
  max_model_len=18944 \
  actor_rollout_ref.rollout.val_kwargs.n=16 \
  actor_rollout_ref.actor.self_distillation.objective=ucsdpo_aux \
  actor_rollout_ref.actor.self_distillation.auxiliary_coef=0.02 \
  actor_rollout_ref.actor.self_distillation.auxiliary_base_loss_mode=vanilla \
  actor_rollout_ref.actor.self_distillation.distillation_topk=100 \
  actor_rollout_ref.actor.self_distillation.alpha=0.5 \
  actor_rollout_ref.actor.self_distillation.dont_reprompt_on_self_success=True \
  actor_rollout_ref.actor.self_distillation.include_environment_feedback=False \
  actor_rollout_ref.actor.self_distillation.uplift_calibration.enable=True \
  actor_rollout_ref.actor.self_distillation.uplift_calibration.jf_policy=ema_teacher_vllm \
  actor_rollout_ref.actor.self_distillation.uplift_calibration.num_samples=1 \
  actor_rollout_ref.actor.self_distillation.uplift_calibration.aggregation=uid \
  actor_rollout_ref.actor.self_distillation.uplift_calibration.reward_upper_bound=1.0 \
  algorithm.rollout_correction.rollout_is=token \
  trainer.total_epochs=1 \
  trainer.test_freq=50 \
  trainer.save_freq=50 \
  trainer.max_actor_ckpt_to_keep=20 \
  trainer.default_local_dir=/mnt/fsx/youtu-agent/jiaxicao/ckpt/ucsdpo_runs/grpo-ucsdpoaux-taco-qwen3-8b-emajf-vllm-h200-6400-260603 \
  trainer.rollout_data_dir=${ROLLOUT_DIR}/train \
  trainer.validation_data_dir=${ROLLOUT_DIR}/val \
  'trainer.logger=["console","tensorboard"]' \
  2>&1 | tee /mnt/fsx/youtu-agent/jiaxicao/logs/ucsdpo/grpo-ucsdpoaux-taco-qwen3-8b-emajf-vllm-h200-6400-260603.log
